<?php
/**
 * See LICENSE.md for license details.
 */
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \PostDirekt\Core\ViewModel\Adminhtml\System\Config\InfoBox\DhlPaketAdditional $viewModel */
$viewModel = $block->getData('view_model');
?>

<div class="section">
    <h3><?= $block->escapeHtml('Deutsche Post Direkt') ?></h3>
    <p>
        <?php $link =  '<a href="' . $block->escapeUrl($viewModel->getConfigGroupLink()) . '">Deutsche Post Direkt</a>'; ?>
        <?= $block->escapeHtml(__('The AUTOCOMPLETE and ADDRESSFACTORY services of %1 ideally complement DHL Shipping via DHL Parcel Germany. Use them to improve the quality of address data in your system.', $link), ['a']) ?>
    </p>
</div>
