<?php
/**
 * See LICENSE.md for license details.
 */
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \PostDirekt\Core\ViewModel\Adminhtml\System\Config\InfoBox\Additional $viewModel */
$viewModel = $block->getData('view_model');
?>

<div class="section">
    <h3><?= $escaper->escapeHtml('Deutsche Post Direkt') ?></h3>
    <p>
        <?= $escaper->escapeHtml(
            __(
                'The AUTOCOMPLETE and ADDRESSFACTORY services of %1Deutsche Post Direkt%2 ideally complement DHL Parcel Germany. Use them to improve the quality of address data in your system.',
                '<a href="' . $escaper->escapeUrl($viewModel->getConfigGroupLink()) . '">',
                '</a>'
            ),
            ['a']
        )
        ?>
    </p>
</div>
